[package]
name = "kaboom_rs"
version = "0.1.0"
authors = ["iOrange <sergey.kudlay@hotmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rayon = "1.0.3"
